apiVersion: v1
kind: PersistentVolume
metadata:
  name: profile-cassandra-data
spec:
  storageClassName: fast-profile
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
