apiVersion: v1
kind: PersistentVolume
metadata:
  name: timeline-cassandra-data
spec:
  storageClassName: fast-timeline
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
