apiVersion: v1
kind: PersistentVolume
metadata:
  name: tweets-cassandra-data
spec:
  storageClassName:  fast-tweet
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
