
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: "miljanabogdanovic/frontend:latest"
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]