apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: miljanabogdanovic/demo:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m