apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: timeline
spec:
  selector:
    matchLabels:
      app: hermes
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: hermes
    spec:
      containers:
        - name: timeline
          image: miljanabogdanovic/timeline:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster