apiVersion: v1 
kind: Service 
metadata: 
  name: tweet-service
  labels:
    app: tweet
spec:
  selector:
    app: tweet
  ports:
    - protocol: "TCP"
      port: 8080 
      targetPort: 8080 
  type: ClusterIP 