apiVersion: v1
kind: PersistentVolume
metadata:
  name: tweets-cassandra-data
  labels:
    type: local
spec:
  storageClassName:  manual # azurefile
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
