apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: tweet
  labels:
    app: tweet
spec:
  selector:
    matchLabels:
      app: tweet
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: tweet
    spec:
      containers:
        - name: tweet
          image: miljanabogdanovic/tweet:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster