apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: profile-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: profile
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50