apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tweet-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tweet
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50