apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline
  labels:
    app: timeline
spec:
  selector:
    matchLabels:
      app: timeline
  replicas: 1
  template:
    metadata:
      labels:
        app: timeline
    spec:
      containers:
        - name: timeline
          image: miljanabogdanovic/timeline:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m