apiVersion: v1 
kind: Service
metadata:
  name: profile-service
  labels:
    app: profile
spec:
  selector:
    app: profile
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: ClusterIP